<a href="https://colab.research.google.com/github/a-tasnim/Machine-Learning-Basics/blob/main/Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
data = pd.read_csv("/content/homeprices.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
import math
median_bedrooms = math.floor(data.bedrooms.median())
median_bedrooms

4

In [ ]:
data.bedrooms = data.bedrooms.fillna(median_bedrooms)

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(data[["area","bedrooms","age"]], data.price)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

#Exercise

In [ ]:
df = pd.read_csv("/content/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [ ]:
!pip install word2number


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install -r requirements.txt


ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


In [ ]:
df.experience = df.experience.fillna("zero").astype(str)
df.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [ ]:
from word2number import w2n


In [ ]:
df.experience = df.experience.apply(w2n.word_to_num)
df.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [ ]:
df.columns = [c.replace("($)", "") for c in df.columns]
df.columns = [c.replace(" ", "_") for c in df.columns]
df.columns


Index(['experience', 'test_score(out_of_10)', 'interview_score(out_of_10)',
       'salary'],
      dtype='object')

In [ ]:
median_score = df['test_score(out_of_10)'].median()

In [ ]:
df['test_score(out_of_10)'] = df['test_score(out_of_10)'].fillna(median_score)
df['test_score(out_of_10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out_of_10), dtype: float64

In [ ]:
df.isnull().sum()

experience                    0
test_score(out_of_10)         0
interview_score(out_of_10)    0
salary                        0
interview_score(out of 10)    0
dtype: int64

In [ ]:
rg = linear_model.LinearRegression()
rg.fit(df[['experience', 'test_score(out_of_10)',	'interview_score(out_of_10)']],df.salary)

LinearRegression()

In [ ]:
rg.predict([[2,9,6]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [ ]:
rg.predict([[12,10,10]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])